### ISSUE TITLE
Broken after 0.12.0 update

### ISSUE THREAD

**Issue by johannes85** [gjcarneiro/yacron#46]
* Yacron version: 0.12.0
* Python version: 3.5.3
* System: Debian Stretch

### Description

After updating yacron to the latest 0.12.0 version it won't run anymore and outputs a error message.

### What I Did

I executed
```
yaxron
```

Error message:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/yacron", line 7, in <module>
    from yacron.__main__ import main
  File "/home/idev/.local/lib/python3.5/site-packages/yacron/__main__.py", line 8, in <module>
    from yacron.cron import Cron, ConfigError
  File "/home/idev/.local/lib/python3.5/site-packages/yacron/cron.py", line 10, in <module>
    from yacron.config import (
  File "/home/idev/.local/lib/python3.5/site-packages/yacron/config.py", line 363
    environ: Dict[str, str] = {}
           ^
SyntaxError: invalid syntax

```

**Comment by gjcarneiro** [comment]
Sorry, I should have made it clear that Python 3.5 is no longer supported.  Try the download binary file yacron-0.12.0-x86_64-unknown-linux-gnu, it should just work.

**Comment by johannes85** [comment]
Ok,  thanks for your answer. I was wondering about that, but the README still said it is supported. I will use the binary.

**Comment by gjcarneiro** [comment]
Yes, you're right.  I've updated the README now.  Thanks for the report.
