### ISSUE TITLE
Error when starting yacron

### ISSUE THREAD

**Issue by moafrancky** [gjcarneiro/yacron#47]
* Yet Another Cron version: 0.12.0
* Python version: 3.8
* Operating System: Alpine

### Description

I want to replace crond by yacron in an Alpine based docker. Unfortunately I have an error when I try to use yacron. 

It was previously working but right now it is not working anymore. I suspect latest ruamel update to break something. What do you think ?

### What I Did

Commands to install yacron
```
python3 -m venv yacronenv && \
. yacronenv/bin/activate && \
pip install yacron
```

Command used to run yacron
```
/yacronenv/bin/yacron -c /home/foo/crontab.yml
```

Configuration file /home/foo/crontab.yml
```
jobs:
  - name: speedtest
    command: /opt/speedtest2mqtt.sh
    shell: /bin/bash
    schedule: "*/5 * * * *"
    env_file: /var/tmp/container.env
    captureStderr: false
    captureStdout: true
    concurrencyPolicy: Forbid

```

```
Traceback (most recent call last):
  File "/yacronenv/bin/yacron", line 8, in <module>
    sys.exit(main())
  File "/yacronenv/lib/python3.8/site-packages/yacron/__main__.py", line 56, in main
    main_loop(_loop)
  File "/yacronenv/lib/python3.8/site-packages/yacron/__main__.py", line 31, in main_loop
    cron = Cron(args.config)
  File "/yacronenv/lib/python3.8/site-packages/yacron/cron.py", line 86, in __init__
    self.update_config()
  File "/yacronenv/lib/python3.8/site-packages/yacron/cron.py", line 145, in update_config
    config, web_config = parse_config(self.config_arg)
  File "/yacronenv/lib/python3.8/site-packages/yacron/config.py", line 434, in parse_config
    config, web_config = parse_config_file(config_arg)
  File "/yacronenv/lib/python3.8/site-packages/yacron/config.py", line 347, in parse_config_file
    return parse_config_string(data, path)
  File "/yacronenv/lib/python3.8/site-packages/yacron/config.py", line 388, in parse_config_string
    doc = strictyaml.load(data, CONFIG_SCHEMA, label=path).data
  File "/yacronenv/lib/python3.8/site-packages/strictyaml/parser.py", line 318, in load
    return generic_load(yaml_string, schema=schema, label=label)
  File "/yacronenv/lib/python3.8/site-packages/strictyaml/parser.py", line 280, in generic_load
    document = ruamelyaml.load(yaml_string, Loader=DynamicStrictYAMLLoader)
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/main.py", line 1067, in load
    return loader._constructor.get_single_data()
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 122, in get_single_data
    return self.construct_document(node)
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 132, in construct_document
    for _dummy in generator:
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 1619, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/yacronenv/lib/python3.8/site-packages/strictyaml/parser.py", line 83, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 155, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 197, in construct_non_recursive_object
    for _dummy in generator:
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 1611, in construct_yaml_seq
    data.extend(self.construct_rt_sequence(node, data))
  File "/yacronenv/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 1322, in construct_rt_sequence
    if self.loader and self.loader.comment_handling is None:
AttributeError: 'DynamicStrictYAMLLoader' object has no attribute 'comment_handling'
```

**Comment by gjcarneiro** [comment]
Thanks for the report.

I probably need to pin a python package dep more tightly to a version.

Meanwhile feel free to use the provided binary version, which was packaged with pyinstaller.

**Comment by gjcarneiro** [comment]
Ah, nevermind about the binary.  If you're using Alpine, I don't think this binary works in Alpine, sorry! :grimacing:

**Comment by moafrancky** [comment]
Thanks for the very fast feedback. I'm building a multi platform (arm7/arm64/x64) docker so I'll wait. :)

**Comment by gjcarneiro** [comment]
I uploaded yacron 0.12.1 that fixes this.  Basically, there was a release of a dependent package, ruamel.yaml version 0.17.5, that has this bug.  Downgrading to 0.17.4 fixes it.

**Comment by vromash** [comment]
@gjcarneiro Hello! Seems like downgrade didn't help. I cannot start yacron anymore, both 0.11.2 and 0.12.1.
I've tried installing just latest yacron, tried downgrading ruamel and yacron as well as reinstalling everything (python 3.8.10). Nothing helped.
Could you please help me?

**Comment by gjcarneiro** [comment]
Looks like ruamel.yaml version 0.17.6 was released last night containing the same bug as 0.17.5 :facepalm: 

I made a new yacron release 0.12.2 that asks for `ruamel.yaml<0.17.4`, which should fix the problem.

**Comment by vromash** [comment]
It worked, thanks a lot!

**Comment by moafrancky** [comment]
Thanks for this fast fix
