### ISSUE TITLE
Handling of schedule-entries not clear enough documented

### ISSUE THREAD

**Issue by andreas-wittig** [gjcarneiro/yacron#74]
* Yet Another Cron version: yacron-0.17.0-x86_64-unknown-linux-gnu
* Python version: - 
* Operating System: Docker/Ubuntu

### Description
It's supposed, that Yacron understands schedule expressions according the original cron - at least the documentation "sounds" so. But it isn't (most probably because yacron has it's own implementation).
The schedule `schedule: "0 22 */100,1-7 * FRI"`  from https://blog.healthchecks.io/2022/09/schedule-cron-job-the-funky-way  delivers
```
root@74e7ce8d1534:/opt/skripte/docker/yacron# ./yacron-0.17.0-x86_64-unknown-linux-gnu -c yacrontab.yaml
Traceback (most recent call last):
  File "yacron", line 3, in <module>
  File "yacron/__main__.py", line 56, in main
  File "yacron/__main__.py", line 31, in main_loop
  File "yacron/cron.py", line 82, in __init__
  File "yacron/cron.py", line 141, in update_config
  File "yacron/config.py", line 472, in parse_config
  File "yacron/config.py", line 435, in parse_config_file
  File "yacron/config.py", line 426, in parse_config_string
  File "yacron/config.py", line 275, in __init__
  File "crontab/_crontab.py", line 386, in __init__
  File "crontab/_crontab.py", line 408, in _make_matchers
  File "crontab/_crontab.py", line 408, in <listcomp>
  File "crontab/_crontab.py", line 204, in __init__
  File "crontab/_crontab.py", line 357, in _parse_crontab
  File "crontab/_crontab.py", line 181, in _assert
ValueError: increment value must be less than 31, you provided 100
[1994] Failed to execute script 'yacron' due to unhandled exception!
```
Besides the unhandled exception (not really a problem) the question arises:  how to find out, which schedule expressions are valid and which are not valid.  The common crontab-generators render useless; e.g. https://crontab.guru, https://www.bennetrichter.de/tools/crontab-generator

Since I don't know python: maybe one ore two reference sites can be linked in the Yacron-Doku, how schedules are handled resp. which schedules are valid?

**Comment by andreas-wittig** [comment]
To make the origin of this issue more clear: One of our jobs needs to run: "1st friday of a month, 8pm".
The common pattern for this type of schedule is:  `[first | last] [Mon | Tue | ... | Sat | Sun] in [month | year]`

This schedule can be expressed with "original cron", but seems not to be possible with yacron.

**Comment by gjcarneiro** [comment]
What "original cron" is that?  There are several traditional cron implementations out there.  The one that comes in Ubuntu, at least, does not seem to support that.  Or if it does, it's not in the man page.

Anyway, yacron uses a python module for this, https://github.com/josiahcarlson/parse-crontab, you would have to convince that project to support those.

**Comment by andreas-wittig** [comment]
My original question "schedule 1st friday every month" was answered by your link to "parse-crontab". Thank you.

**Comment by andreas-wittig** [comment]
proposal for docu extension merged by gjcarneiro
